### ISSUE TITLE
Incorrect reference to JS and enabled-check not working properly

### ISSUE THREAD

**Issue by teppokoivula** [cybermano/CustomNotes#5]
Hey @cybermano!

Just gave this module a try and ran into a couple of issues:

- The module tries to get JS file from CustomNotes_JS directory, which doesn't exist (https://github.com/cybermano/CustomNotes/blob/main/CustomNotes.module#L199)
- The custom notes button only shows up if enable_module is 0, which at least in my case can never happen; it's always null or 1 (https://github.com/cybermano/CustomNotes/blob/main/CustomNotes.module#L24 and https://github.com/cybermano/CustomNotes/blob/main/CustomNotes.module#L47)

Fixed these locally by removing the CustomNotes_JS part from the JS path and by instead of `$this->enable_module == 0` checking for `!$this->enable_module`. After those modifications the module seemed to work splendidly :)

**Comment by teppokoivula** [comment]
Just noticed another issue: CustomNotes.js was always loaded in admin, and in some cases it would break config screens for other modules. In the linked PR I've added a couple of fixes for this:

- In CustomNotes.js check that form action includes CustomNotes. Now even if the script is loaded somehow, it won't cause issues.
- In CustomNotes.module move script injection from __construct() to init() and add basic validation that we're in the CustomNotes admin screen before loading it.

**Comment by cybermano** [comment]
Hi @Teppo
Thanks for your time and support.
I will check your debug asap but I'm pretty sure your eyes will bost perfectly my clumsy mistakes.
👍🏻
